# Generated by Django 3.2.6 on 2021-09-19 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210918_1846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='bigoraphy',
            new_name='biography',
        ),
    ]
